services:
  db:
    image: pgvector/pgvector:pg15
    container_name: postgres
    environment:
      POSTGRES_DB: spotify_rag
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d spotify_rag"]
      interval: 5s
      timeout: 5s
      retries: 5

  ingest:
    container_name: ingest
    # profiles:
    #   - cli
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    stdin_open: true # docker run -i
    tty: true # docker run -t

    environment:
      - DB_HOST=db
      - OLLAMA_HOST=http://host.docker.internal:11434

    volumes:
      - ../logs:/app/logs
      - ../test_data:/app/test_data
      - ./.spotify_token_cache:/app/.spotify_token_cache
      - ./src:/app/src
      - hf_cache:/root/.cache/huggingface
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  hf_cache:
